Repository NatureTeam/NatureKarly, pull requests merged in 2023-03, with the labels that each got.

#8 :lipstick: [추가] tokens.js
  src/theme/tokens.js
Labels: Style

#11 Setting/10 upgrade storybook
  .storybook/main.js
  jsconfig.json
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/app/App.jsx
  src/component/Button/Button.jsx
  src/component/Button/Button.module.css
  src/component/Button/Button.stories.js
  src/component/index.js
  src/theme/ThemeContext.jsx
  src/theme/tokens.js
  src/theme/utils.js
  vite.config.js
Labels: Setting

#13 🔧[수정] eslint 수정 #12
  .eslintrc.js
Labels: Setting, bug

#18 :bug: [수정] storybook 명렁어 실행 경로 및 components 폴더명 수정
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/A11yHidden/A11yHidden.jsx
  src/components/A11yHidden/A11yHidden.module.css
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Button/Button.stories.js
  src/components/index.js
Labels: Rename, bug

#19 Feature/14 design button
  package.json
  pnpm-lock.yaml
  src/app/App.jsx
  src/component/Button/Button.jsx
  src/component/Button/Button.module.css
  src/main.jsx
  src/styles/theme.css
  src/theme/tokens.js
Labels: Feature

#22 Feature/9 input components
  .storybook/preview.js
  src/assets/isChecked=true.svg
  src/assets/search-close.svg
  src/components/Input/Input.jsx
  src/components/Input/Input.module.css
  src/components/Input/Input.stories.js
  src/components/index.js
Labels: Feature, Design

#27 Setting, Feature/ eslintrc.js 수정 및 Container 컴포넌트 디자인
  .eslintrc.js
  src/components/Container/Container.jsx
  src/components/Container/Container.module.css
  src/components/Container/Container.stories.jsx
Labels: Setting, Feature, bug

#38 Feature/24 design icon component
  src/app/App.jsx
  src/assets/icons/Icon/header/type=_TraditionalLiquor.svg
  src/components/Button/Button.module.css
  src/components/Button/Button.stories.js
  src/components/IconComponent/IconComponent.jsx
  src/components/IconComponent/IconComponent.module.css
  src/components/IconComponent/IconComponent.stories.js
Labels: Feature

#42 Feature/36 label components
  src/assets/icons/Input/search-close.svg
  src/components/Input/Input.jsx
  src/components/Input/Input.module.css
  src/components/Input/Input.stories.jsx
  src/components/Label/Label.jsx
  src/components/Label/Label.module.css
  src/components/Label/Label.stories.jsx
  src/components/index.js
  vite.config.js
Labels: Feature, Design, Rename, Style, bug

#40 Feature/39 Tag component 디자인
  src/components/Tag/Tag.jsx
  src/components/Tag/Tag.module.css
  src/components/Tag/Tag.stories.jsx
Labels: Feature

#46 Fix/css 정렬 안됨 수정
  src/components/Container/Container.module.css
Labels: bug

#51 Feature/44 table component design
  src/components/EmptyContent/EmptyContent.jsx
  src/components/EmptyContent/EmptyContent.module.css
  src/components/EmptyContent/EmptyContent.stories.jsx
  src/components/InquiryAnswer/InquiryAnswer.jsx
  src/components/InquiryAnswer/InquiryAnswer.stories.jsx
  src/components/InquiryContent/InquiryContent.jsx
  src/components/InquiryContent/InquiryContent.module.css
  src/components/InquiryContent/InquiryContent.stories.jsx
  src/components/InquiryQuestion/InquiryQuestion.jsx
  src/components/InquiryQuestion/InquiryQuestion.stories.jsx
  src/components/InquiryTitle/InquiryTitle.jsx
  src/components/InquiryTitle/InquiryTitle.stories.jsx
  src/components/NormalNoticeContent/NormalNoticeContent.jsx
  src/components/NormalNoticeContent/NormalNoticeContent.module.css
  src/components/NormalNoticeContent/NormalNoticeContent.stories.jsx
  src/components/PageMoveButtons/PageMoveButtons.jsx
  src/components/PageMoveButtons/PageMoveButtons.module.css
  src/components/PageMoveButtons/PageMoveButtons.stories.jsx
  src/components/ProductInquirySection/ProductInquirySection.jsx
  src/components/ProductInquirySection/ProductInquirySection.stories.jsx
  src/components/ProductInquiryTable/ProductInquiryTable.jsx
  src/components/ProductInquiryTable/ProductInquiryTable.module.css
  src/components/ProductInquiryTable/ProductInquiryTable.stories.jsx
  src/components/ProductReviewSection/ProductReviewSection.jsx
  src/components/ProductReviewSection/ProductReviewSection.module.css
  src/components/ProductReviewSection/ProductReviewSection.stories.jsx
  src/components/ProductReviewTable/ProductReviewTable.jsx
  src/components/ProductReviewTable/ProductReviewTable.stories.jsx
  src/components/ProductTable/ProductTable.jsx
  src/components/ProductTable/ProductTable.module.css
  src/components/ProductTable/ProductTable.stories.jsx
  src/components/ReviewDescription/ReviewDescription.jsx
  src/components/ReviewDescription/ReviewDescription.module.css
  src/components/ReviewDescription/ReviewDescription.stories.jsx
  src/components/ReviewTableContent/ReviewTableContent.jsx
  src/components/ReviewTableContent/ReviewTableContent.module.css
  src/components/ReviewTableContent/ReviewTableContent.stories.jsx
  src/components/TableNoticeHeader/TableNoticeHeader.jsx
  src/components/TableNoticeHeader/TableNoticeHeader.module.css
  src/components/TableNoticeHeader/TableNoticeHeader.stories.jsx
  src/components/Tag/Tag.jsx
  src/components/Tag/Tag.module.css
  src/components/index.js
Labels: Feature, Accessibility

#64 Feature/53 pop up component design
  src/components/InquiryPlaceHolder/InquiryPlaceHolder.jsx
  src/components/InquiryPlaceHolder/InquiryPlaceHolder.module.css
  src/components/InquiryPlaceHolder/InquiryPlaceHolder.stories.jsx
  src/components/ProductInquiryPopUp/ProductInquiryPopUp.jsx
  src/components/ProductInquiryPopUp/ProductInquiryPopUp.module.css
  src/components/ProductInquiryPopUp/ProductInquiryPopUp.stories.jsx
  src/components/ProductPopUpButtons/ProductPopUpButtons.jsx
  src/components/ProductPopUpButtons/ProductPopUpButtons.module.css
  src/components/ProductPopUpButtons/ProductPopUpButtons.stories.jsx
  src/components/ProductPopUpContent/ProductPopUpContent.jsx
  src/components/ProductPopUpContent/ProductPopUpContent.module.css
  src/components/ProductPopUpContent/ProductPopUpContent.stories.jsx
  src/components/ProductPopUpInput/ProductPopUpInput.jsx
  src/components/ProductPopUpInput/ProductPopUpInput.module.css
  src/components/ProductPopUpInput/ProductPopUpInput.stories.jsx
  src/components/ProductPopUpTitle/ProductPopUpTitle.jsx
  src/components/ProductPopUpTitle/ProductPopUpTitle.module.css
  src/components/ProductPopUpTitle/ProductPopUpTitle.stories.jsx
  src/components/ProductReviewPopUp/ProductReviewPopUp.jsx
  src/components/ProductReviewPopUp/ProductReviewPopUp.module.css
  src/components/ProductReviewPopUp/ProductReviewPopUp.stories.jsx
  src/components/ProductWriteForm/ProductWriteForm.jsx
  src/components/ProductWriteForm/ProductWriteForm.module.css
  src/components/ProductWriteForm/ProductWriteForm.stories.jsx
  src/components/ReviewPlaceHolder/ReviewPlaceHolder.jsx
  src/components/ReviewPlaceHolder/ReviewPlaceHolder.module.css
  src/components/ReviewPlaceHolder/ReviewPlaceHolder.stories.jsx
  src/components/index.js
Labels: Feature, Accessibility

#52 Feature/50 internal link move list component design
  src/components/InternalLinkMove/InternalLinkMove.jsx
  src/components/InternalLinkMove/InternalLinkMove.module.css
  src/components/InternalLinkMove/InternalLinkMove.stories.jsx
  src/components/InternalLinkMoveTest/InternalLinkMoveTest.jsx
  src/components/InternalLinkMoveTest/InternalLinkMoveTest.module.css
  src/components/InternalLinkMoveTest/InternalLinkMoveTest.stories.jsx
  src/components/InternalLinkMoves/InternalLinkMoves.jsx
  src/components/InternalLinkMoves/InternalLinkMoves.module.css
  src/components/InternalLinkMoves/InternalLinkMoves.stories.jsx
  src/components/index.js
Labels: Feature, Accessibility

#61 Feature/16 navigation
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
  src/app/App.jsx
  src/assets/Hamburger.svg
  src/assets/icons/Icon/footer/logo_isms.svg
  src/assets/icons/Icon/footer/logo_privacy.svg
  src/assets/icons/Icon/footer/logo_tosspayments.svg
  src/assets/icons/Icon/footer/logo_wooriBank.svg
  src/assets/icons/Icon/header/Cart.svg
  src/assets/icons/Icon/header/IconDown1.svg
  src/assets/icons/Icon/header/Search.svg
  src/components/Button/Button.jsx
  src/components/Container/Container.module.css
  src/components/Layout/Layout.jsx
  src/components/Layout/Layout.module.css
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.module.css
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.module.css
  src/components/index.js
  src/styles/theme.css
  src/utils/getPathFromBaseUrl.js
  src/utils/index.js
Labels: Feature

#57 Feature/31 product detail table
  .github/ISSUE_TEMPLATE/✅-feature.md
  .github/ISSUE_TEMPLATE/🐞-bug.md
  .github/ISSUE_TEMPLATE/📝-document.md
  .github/ISSUE_TEMPLATE/🔧-refactor.md
  .github/pull_request_template.md
  src/assets/icons/Icon/product/Bell.svg
  src/components/Counter/Counter.jsx
  src/components/Counter/Counter.module.css
  src/components/Heading/Heading.jsx
  src/components/Heading/Heading.module.css
  src/components/Logo/Logo.jsx
  src/components/ProductDetailTable/ProductDetailTable.jsx
  src/components/ProductDetailTable/ProductDetailTable.module.css
  src/components/ProductDetailTable/ProductInformation/ProductInformation.jsx
  src/components/ProductDetailTable/ProductInformation/ProductInformation.module.css
  src/components/ProductDetailTable/ProductPrice/ProductPrice.jsx
  src/components/ProductDetailTable/ProductPrice/ProductPrice.module.css
Labels: Feature, Design

#58 Feature/49 cart table
  src/components/Cart/Cart.jsx
  src/components/Cart/Cart.module.css
  src/components/Cart/CartTable/CartTable.jsx
  src/components/Cart/CartTable/CartTable.module.css
  src/components/Cart/CartTable/CartTableComponent/CartTableComponent.jsx
  src/components/Cart/CartTable/CartTableComponent/CartTableComponent.module.css
  src/components/Cart/OrdererTable/OrdererTable.jsx
  src/components/Cart/OrdererTable/OrdererTable.module.css
  src/styles/theme.css
Labels: Feature, Design

#55 Feature/35 main components
  src/assets/banner/banner01.png
  src/assets/banner/banner02.png
  src/assets/banner/banner03.png
  src/components/Product/Product.jsx
  src/components/Product/Product.module.css
  src/components/Title/Title.jsx
  src/components/Title/Title.module.css
  src/components/index.js
  src/pages/Main/MainPage.jsx
  src/pages/Main/MainPage.module.css
  src/pages/Main/MainPage.swiper.css
  src/styles/global.css
Labels: Feature

#71 Feature/66 price calculation
  .husky/pre-commit
  src/components/Button/Button.jsx
  src/components/Counter/Counter.jsx
  src/components/Counter/Counter.module.css
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Layout/Layout.jsx
  src/components/Logo/Logo.jsx
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.module.css
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.module.css
  src/components/ProductDetailTable/ProductDetailTable.jsx
  src/components/ProductDetailTable/ProductPrice/ProductPrice.jsx
  src/components/index.js
  src/utils/getPathFromBaseUrl.js
Labels: Feature

#73 Feature/65 pop up modal
  index.html
  src/@store/modalStates.js
  src/@store/popUpTextState.js
  src/components/InternalLinkMoveTest/InternalLinkMoveTest.jsx
  src/components/InternalLinkMoveTest/InternalLinkMoveTest.module.css
  src/components/ModalWindow/ModalWindow.jsx
  src/components/ModalWindow/ModalWindow.module.css
  src/components/ProductInquirySection/ProductInquirySection.jsx
  src/components/ProductPopUpButtons/ProductPopUpButtons.jsx
  src/components/ProductPopUpContent/ProductPopUpContent.jsx
  src/components/ProductPopUpInput/ProductPopUpInput.jsx
  src/components/ProductPopUpTitle/ProductPopUpTitle.jsx
  src/components/ProductReviewSection/ProductReviewSection.jsx
  src/components/ReviewDescription/ReviewDescription.jsx
  src/components/ReviewWriteButton/ReviewWriteButton.jsx
  src/components/ReviewWriteButton/ReviewWriteButton.module.css
  src/components/index.js
Labels: Feature

#72 Feature/56 productlist components
  package-lock.json
  package.json
  src/app/App.jsx
  src/components/Input/Input.module.css
  src/components/Label/Label.jsx
  src/components/Label/Label.module.css
  src/components/Product/Product.jsx
  src/components/Product/Product.module.css
  src/components/TableNoticeHeader/TableNoticeHeader.jsx
  src/components/Title/Title.jsx
  src/components/Title/Title.module.css
  src/components/index.js
  src/firebase/app.js
  src/firebase/auth/README.md
  src/firebase/auth/index.js
  src/firebase/auth/useAuthState.js
  src/firebase/auth/useSignIn.js
  src/firebase/auth/useSignOut.js
  src/firebase/auth/useSignUp.js
  src/firebase/firestore/README.md
  src/firebase/firestore/index.js
  src/firebase/firestore/useCreateAuthUser.js
  src/firebase/firestore/useCreateData.js
  src/firebase/firestore/useDataState.js
  src/firebase/firestore/useDeleteData.js
  src/firebase/firestore/useReadData.js
  src/firebase/firestore/useUpdateData.js
  src/firebase/firestore/useWriteBatchData.js
  src/firebase/storage/README.md
  src/firebase/storage/index.js
  src/firebase/storage/useDownloadURL.js
  src/firebase/storage/useUploadFile.js
  src/pages/Main/MainPage.jsx
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.css
Labels: Feature

#76 Feature/75 header scroll
  src/assets/mainPopUp.svg
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Layout/Layout.jsx
  src/components/Link/Link.jsx
  src/components/Link/Link.module.css
  src/components/MainPopUp/MainPopUp.jsx
  src/components/MainPopUp/MainPopUp.module.css
  src/components/Menu/Menu.jsx
  src/components/Menu/Menu.module.css
  src/components/Nav/Nav.jsx
  src/components/Nav/Nav.module.css
  src/components/NavSide/NavSide.jsx
  src/components/NavSide/NavSide.module.css
  src/components/index.js
Labels: Feature, Style

#74 Setting/45 firebase auth
  package.json
  pnpm-lock.yaml
  src/@store/signUpState.js
  src/app/App.css
  src/app/App.jsx
  src/app/App.module.css
  src/assets/icons/Icon/common/Direction=Right.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Fieldset/Fieldset.jsx
  src/components/Fieldset/Fieldset.module.css
  src/components/IconComponent/IconComponent.jsx
  src/components/IconComponent/IconComponent.module.css
  src/components/Input/Checkbox/AdditionalInput.jsx
  src/components/Input/Checkbox/EtcInput.jsx
  src/components/Input/General/BirthInput.jsx
  src/components/Input/General/EmailInput.jsx
  src/components/Input/General/IdInput.jsx
  src/components/Input/General/Input.jsx
  src/components/Input/General/Input.module.css
  src/components/Input/General/Input.stories.jsx
  src/components/Input/General/NameInput.jsx
  src/components/Input/General/PhoneInput.jsx
  src/components/Input/General/PwInput.jsx
  src/components/Input/General/RepwInput.jsx
  src/components/Input/Input.jsx
  src/components/Input/Radio/GenderInput.jsx
  src/components/InputValidation/Birth/BirthValidation.jsx
  src/components/InputValidation/Birth/BirthValidation.module.css
  src/components/InputValidation/Email/EmailValidation.jsx
  src/components/InputValidation/Email/EmailValidation.module.css
  src/components/InputValidation/Id/IdValidation.jsx
  src/components/InputValidation/Id/IdValidation.module.css
  src/components/InputValidation/Name/NameValidation.jsx
  src/components/InputValidation/Name/NameValidation.module.css
  src/components/InputValidation/Password/PasswordValidation.jsx
  src/components/InputValidation/Password/PasswordValidation.module.css
  src/components/InputValidation/Phone/PhoneValidation.jsx
  src/components/InputValidation/Phone/PhoneValidation.module.css
  src/components/InputValidation/RePassword/RePasswordValidation.jsx
  src/components/InputValidation/RePassword/RePasswordValidation.module.css
  src/components/Label/Label.jsx
  src/components/Label/Label.module.css
  src/components/index.js
  src/firebase/app.js
  src/firebase/auth.js
  src/hook/useDocumentTitle.js
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/SignUp.module.css
  src/styles/theme.css
  src/util/debounce.js
  src/util/validator.js
Labels: Setting, Feature, Style, bug

#78 Develop/ 페이지 생성 및 수정
  src/components/Cart/CartTable/CartTableComponent/CartTableComponent.jsx
  src/components/ProductDetailTable/ProductDetailTable.module.css
  src/pages/CartPage/CartPage.jsx
  src/pages/ProductDetail/ProductDetail.jsx
Labels: Feature

#80 Hotfix/79 product detail table의 button과 input 스타일링 깨짐 현상 수정
  src/components/Button/Button.module.css
  src/components/Counter/Counter.jsx
  src/components/Counter/Counter.module.css
Labels: Design, bug

#81 Develop/ Router 연결 및 불필요한 스타일 제거, 변경
  src/app/App.jsx
  src/components/Footer/Footer.module.css
  src/components/Header/Header.jsx
  src/components/Layout/Layout.jsx
  src/components/Logo/Logo.jsx
  src/components/ModalWindow/ModalWindow.module.css
  src/components/Product/Product.jsx
  src/pages/CartPage/CartPage.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/SignUp/SignUp.jsx
Labels: Feature, Style

#84 Hotfix/83 buttons css fix
  src/components/Link/Link.jsx
  src/components/Link/Link.module.css
  src/components/ProductPopUpButtons/ProductPopUpButtons.module.css
  src/components/ReviewWriteButton/ReviewWriteButton.jsx
  src/components/ReviewWriteButton/ReviewWriteButton.module.css
Labels: Remove, Design, bug

#87 Hotfix / 메인, 상품리스트 css 수정
  index.html
  src/assets/favicon/android-chrome-192x192.png
  src/assets/favicon/android-chrome-512x512.png
  src/assets/favicon/apple-touch-icon.png
  src/assets/favicon/favicon-16x16.png
  src/assets/favicon/favicon-32x32.png
  src/assets/favicon/favicon.ico
  src/assets/favicon/site.webmanifest
  src/components/Product/Product.jsx
  src/components/Product/Product.module.css
  src/components/index.js
  src/pages/Main/MainPage.jsx
  src/pages/Main/MainPage.swiper.css
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.css
  src/styles/global.css
Labels: Accessibility, Design, bug

#88 Hotfix/index.html lang, title 수정, description추가
  index.html
Labels: Update
